// console.log("" + 1 + 0)
// console.log(true + false)
// console.log(6 / "3")
// console.log("  -9  " + 5)
// console.log(null + 1)
// console.log(undefined + 1)
// console.log(10 > 20)
// console.log("a" > "b")
// console.log("2" > "12")
// console.log("2" > 1)
// console.log(undefined == null)
// console.log(undefined === null)
            